FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Create directories for data and models
RUN mkdir -p /app/data_from_2024 /app/data && \
    chmod 777 /app/data_from_2024 /app/data

# Command to run the training script
CMD ["python", "prepare_dataset.py"]}